# general settings
name: SR_Self_Align_x4_sesam
model_type: SRGANModelDeform
scale: 4 #sr upsample scale
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: data_ovarian
    type: PairedImageDataset
    dataroot_gt: datasets/data_ovarian/train_GT_rename_crop_sub.lmdb
    dataroot_lq: datasets/data_ovarian/train_input_rename_warped_crop_sub.lmdb
    # (for lmdb)
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: data_ovarian
    type: PairedImageDataset
    dataroot_gt: datasets/data_ovarian/val_GT
    dataroot_lq: datasets/data_ovarian/val_input
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBDCNNetSESAM
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 64
  num_block: 20
  num_grow_ch: 32
  deformable_groups: 8
  num_extract_block: 10

network_d:
  type: Discriminator
  in_channels: 1
  use_sigmoid: False

# path
path:
  pretrain_network_g:
#  strict_load_g: true
#  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 0.1
    style_weight: 0
    norm_img: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-2

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
